### ISSUE TITLE
om-cli/om-linux

### ISSUE THREAD

**Issue by caresourceplatform** [rahul-kj/concourse-vsphere#27]
This worked on July 3rd 2019
Stopped working on try on July 10th 2019

Receiving this error: 
Upload-Product Job
+ chmod +x om-cli/om-linux
chmod: cannot access 'om-cli/om-linux': No such file or directory

OM job output:
tag | 2.0.1
body	

Was a release to make sure that `brew upgrade` works.
commit_sha	
e2a24e1466d17d7a32c7a36be98e9f87e36f9410
name	
2.0.1
tag	
2.0.1
url	
https://github.com/pivotal-cf/om/releases/tag/2.0.1

**Comment by aegershman** [comment]
Just a heads up, this is likely because they changed their release/naming strategy. See also:

- https://github.com/pivotal-cf/om/blob/master/CHANGELOG.md#breaking-change
- https://github.com/pivotal-cf/om/blob/master/CHANGELOG.md#versioning
- https://github.com/pivotal-cf/om/commit/7ae3101d2f64ab6ba34e792636bd74b941bb78bc
- https://github.com/starkandwayne/homebrew-cf/issues/17#issue-463986027

**Comment by rahulkj** [comment]
Thanks, the docker image was patched. Closing the issue as this should have been resolved by now. If not, then please re-open the issue. 

Apologies for the late reply :)
